sudo: false
language: node_js
node_js:
  - "4.5"

before_install:
# Get installer script.
  - wget https://github.com/nodeGame/nodegame-test/raw/master/nodegame-installer.js
  - chmod a+x nodegame-installer.js

install:
  - node nodegame-installer.js @dev --install-dir nodegame --no-spinner

script:
# Add nodegame-server tests here.

# Test Ultimatum game.
  - ls nodegame/ -la
  - ls nodegame/games/ultimatum-game/ -la
  - ls nodegame/games/ultimatum-game/bin/ -la 
  - cd nodegame/games/ultimatum-game/
  - ./bin/run-standalone-test-v4.sh
