sudo: false
language: node_js
node_js:
  - 6
  - 7
  - 8

before_install:
# Get installer script.
  - wget https://github.com/nodeGame/nodegame-test/raw/master/nodegame-installer.js
  - chmod a+x nodegame-installer.js

install:
  - node nodegame-installer.js @dev --install-dir nodegame --no-spinner --branch v4

script:
# Add nodegame-server tests here.

# Test Ultimatum game.
  - ls nodegame/node_modules/ -la
  - ./bin/run-standalone-test-v4.sh
